<?php
    $_order = Mage::getSingleton('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
    $_items = $_order->getAllVisibleItems();
    $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
?>

<!-- Start Photoslurp Embed Code -->
<script type="text/javascript">
    var photoSlurpTrackingSettings = {
        products: {
        <?php foreach($_items as $item):?>
            '<?php echo $item->getSku() ?>': {count:<?php echo $item->getQtyOrdered() ?>, price:<?php echo $item->getPrice()  ?>, curency: '<?php echo $currency_code ?>'},
        <?php endforeach; ?>
        }
    };
    (function() {
        var d=document,
            h=d.getElementsByTagName('head')[0],
            s=d.createElement('script');
        s.type='text/javascript';
        s.async=true;
        s.src='//static.photoslurp.com/widget/v1/tracking_notify.js';
        h.appendChild(s);
    }());
</script>
<!-- End Photoslurp Embed Code -->