
<?php

	$_locale = Mage::app()->getLocale()->getLocaleCode();

	$_store_id = Mage::app()->getStore()->getStoreId();

	$_product = $this->getProduct();

	$_skus = array();

	if ($_product){

		$_skus[] = $_product->getSku();

		if($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE){

			$childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null,$_product);
			foreach($childProducts as $child) {
				$_skus[] =  $child->getSku();
			}

		}
	}

	$_product_id_str = "['".implode("','",$_skus)."']";

    $_widget = $this->getWidget();

?>

<?php if($_widget->getId()):

	$_widget_types = Photoslurp_PsWidget_Block_Adminhtml_Pswidget_Grid::getValueArray5();
	$_page_types = Photoslurp_PsWidget_Block_Adminhtml_Pswidget_Grid::getValueArray10();

    $_widget_container_id       =   'ps_container'.$_widget->getId();//$_widget->getWidgetContainerId();
    $_widget_type               =   $_widget_types[$_widget->getWidgetType()]['label'];
	$_random_order              =   $_widget -> getRandomOrder();
	$_allow_empty               =   $_widget -> getAllowEmpty();
	$_autoscroll_limit			=   $_widget -> getAutoscrollLimit();
	$_album_id                  =   $_widget -> getAlbumId();
    $_lang                      =   $_locale.'_'.$_store_id;
    $_widget_id                 =   $_widget -> getWidgetId();
    $_image_height              =   $_widget -> getImageHeight();
    $_image_width               =   $_widget -> getImageWidth();
    $_show_submit               =   $_widget -> getShowSubmit();
    $_submit_text               =   $this->getLangValue($_widget->getId(),$_store_id,'submit_text');
	$_shop_this_look_text       =   $this->getLangValue($_widget->getId(),$_store_id,'shop_this_look_text');
	$_cta_button       			=   $this->getLangValue($_widget->getId(),$_store_id,'cta_button');
	$_load_more_text       		=   $this->getLangValue($_widget->getId(),$_store_id,'load_more_text');

	$_enable_ga					=	$_widget -> getEnableGa();
	$_page_limit                =   $_widget -> getPageLimit();
    $_page_type                 =   $_page_types[$_widget -> getPageType()]['label'];

    $_add_photos_img            =   $this->getLangValue($_widget->getId(),$_store_id,'add_photos_img');
    $_social_icons              =   $_widget -> getSocialIcons();
	$_social_count              =   $_widget -> getSocialCount();

	$_note_add_pics_text        =   $this->getLangValue($_widget->getId(),$_store_id,'note_add_pics_text');

	$_submission_form_css_url	=	$_widget -> getSubmissionFormCssUrl();

	$_init_delay				=   $_widget -> getInitDelay();
	$_thumb_overlay				=	$_widget -> getThumbOverlay();
	$_varying_thumb_sizes		=	$_widget -> getVaryingThumbSizes();
	$_auto_scroll_carousel 		=	$_widget -> getAutoScrollCarousel();
	$_one_photo_per_line 		=	$_widget -> getOnePhotoPerLine();

	$_analytics_cookie_ttl		=   $_widget -> getAnalyticsCookieTtl();

	$_toc_link       			=   $_widget -> getTocLink();

	$_strict_products			=	$_widget -> getStrictProducts();
	$_empty_threshold			=	$_widget -> getEmptyThreshold();

	$_in_stock_only 			= 	$_widget -> getInStockOnly();
	$_rights_cleared_only		= 	$_widget -> getRightsClearedOnly();
	$_assigned_only				= 	$_widget -> getAssignedOnly();
	$_visible_products			= 	$_widget -> getVisibleProducts();

	$_additional_params 		=	$_widget -> getAdditionalParams();
	$_collections               =   $_widget -> getCollections();
	$_cookie_domain				=	$_widget -> getCookieDomain();


//STYLE PARAMETERS

    $_style_submissionform_colourtop        =   $_widget->getData('style_submissionform_colourtop');
    $_style_submissionform_colourbutton     =   $_widget->getData('style_submissionform_colourbutton');
    $_style_submissionform_font             =   $_widget->getData('style_submissionform_font');

    $_style_taggingtitle_font_family        =   $_widget->getData('style_taggingtitle_font_family');
    $_style_taggingtitle_font_style         =   $_widget->getData('style_taggingtitle_font_style');
    $_style_taggingtitle_font_weight        =   $_widget->getData('style_taggingtitle_font_weight');
    $_style_taggingtitle_font_color         =   $_widget->getData('style_taggingtitle_font_color');
    $_style_taggingtitle_font_size          =   $_widget->getData('style_taggingtitle_font_size');

    $_style_thumbnail_bg_color              =   $_widget->getData('style_thumbnail_bg_color');
    $_style_thumbnail_border_color          =   $_widget->getData('style_thumbnail_border_color');

    $_style_carousel_bg_color               =   $_widget->getData('style_carousel_bg_color');

    $_style_popup_bg_color                  =   $_widget->getData('style_popup_bg_color');
    $_style_popup_title_font_family         =   $_widget->getData('style_popup_title_font_family');
    $_style_popup_title_font_style          =   $_widget->getData('style_popup_title_font_style');
    $_style_popup_title_font_weight         =   $_widget->getData('style_popup_title_font_weight');
    $_style_popup_title_font_color          =   $_widget->getData('style_popup_title_font_color');

    $_style_source_font_family              =   $_widget->getData('style_source_font_family');
    $_style_source_font_style               =   $_widget->getData('style_source_font_style');
    $_style_source_font_weight              =   $_widget->getData('style_source_font_weight');
    $_style_source_font_color               =   $_widget->getData('style_source_font_color');

    $_style_productcaptionshop_font_family  =   $_widget->getData('style_productcaptionshop_font_family');
    $_style_productcaptionshop_font_style   =   $_widget->getData('style_productcaptionshop_font_style');
    $_style_productcaptionshop_font_weight  =   $_widget->getData('style_productcaptionshop_font_weight');
    $_style_productcaptionshop_font_color   =   $_widget->getData('style_productcaptionshop_font_color');

    $_style_productdescription_font_family  =   $_widget->getData('style_productdescription_font_family');
    $_style_productdescription_font_style   =   $_widget->getData('style_productdescription_font_style');
    $_style_productdescription_font_weight  =   $_widget->getData('style_productdescription_font_weight');
    $_style_productdescription_font_color   =   $_widget->getData('style_productdescription_font_color');
?>




<div id="<?php echo $_widget_container_id ?>" style="clear:both" class="ps-container">
    <script data-type="photoslurp">

        if(!photoSlurpWidgetSettings) {
            var photoSlurpWidgetSettings = {};
        }

        (function() {
            photoSlurpWidgetSettings['<?php echo $_widget_container_id ?>'] = {
				widgetType:     '<?php echo $_widget_type ?>',
				randomOrder: 	<?php echo ($_random_order)?'true':'false' ?>,
				allowEmpty: 	<?php echo ($_allow_empty)?'true':'false' ?>,
				albumId:         <?php echo $_album_id ?>,
				lang:           '<?php echo $_lang ?>',
				widgetId:       '<?php echo $_widget_id ?>',
<?php
	if($_widget->getWidgetType() == '1'){
		echo $this->__("				imageHeight: '%spx',\n",$_image_height);
	}else{
		echo $this->__("				imageWidth: '%spx',\n",$_image_width);
	}
?>
				showSubmit:      <?php echo ($_show_submit)?'true':'false' ?>,
				submitText:     '<?php echo addslashes($_submit_text) ?>',
<?php if($_shop_this_look_text): ?>
				shopThisLookText:'<?php echo addslashes($_shop_this_look_text) ?>',
<?php endif; ?>
				autoscrollLimit: <?php echo $_autoscroll_limit ?>,
				page_limit:      <?php echo $_page_limit ?>,
				pageType:       '<?php echo $_page_type ?>',
				productId:      <?php echo $_product_id_str ?>,
				addPhotosImg:   '<?php echo $_add_photos_img ?>',
				socialIcons:     <?php echo ($_social_icons)?'true':'false' ?>,
				noteAddPicsText:'<?php echo addslashes($_note_add_pics_text) ?>',
				noteAddPicsIcons: {
					facebook: false,
					twitter: false,
					instagram: false
				},
<?php
if ($_collections)	{
	$strings = explode(",",$_collections);
	for($i = 0; $i < count($strings); $i++){
		$strings[$i] = trim($strings[$i]);
	}
	$str = "'".implode("','",$strings)."'";
	echo $this->__("				collection: [%s],\n", $str);
}
if ($_load_more_text) 			echo $this->__("				loadMoreText: '%s',\n", addslashes($_load_more_text));
if ($_init_delay)     			echo $this->__("				initDelay: %s,\n", $_init_delay);
if ($_cta_button)     			echo $this->__("				ctaButton: '%s',\n", addslashes($_cta_button)) ;
if ($_analytics_cookie_ttl) 	echo $this->__("				analyticsCookieTTL: %s,\n", $_analytics_cookie_ttl) ;
if ($_toc_link) 				echo $this->__("				tocLink: '%s',\n", addslashes($_toc_link));
if ($_submission_form_css_url) 	echo $this->__("				submissionformCSSURL: '%s',\n", $_submission_form_css_url) ;
if ($_visible_products) 		echo $this->__("				visibleProducts: '%s',\n", $_visible_products);
if ($_cookie_domain) 			echo $this->__("				cookieDomain: '%s',\n", addslashes($_cookie_domain));

$anvanced_enabled = array();
if($_enable_ga) $anvanced_enabled[] = 'enableGA';
if($_social_count) $anvanced_enabled[] = 'socialCount';
if($_thumb_overlay) $anvanced_enabled[] = 'thumbOverlay';
if($_varying_thumb_sizes) $anvanced_enabled[] = 'varyingThumbSizes';
if($_auto_scroll_carousel) $anvanced_enabled[] = 'autoScrollCarousel';
if($_one_photo_per_line) $anvanced_enabled[] = 'onePhotoPerLine';
if($_strict_products) $anvanced_enabled[] = 'strictProducts';
if($_empty_threshold) $anvanced_enabled[] = 'emptyThreshold';
if($_in_stock_only) $anvanced_enabled[] = 'inStockOnly';
if($_rights_cleared_only) $anvanced_enabled[] = 'rightsClearedOnly';
if($_assigned_only) $anvanced_enabled[] = 'assignedOnly';

foreach ($anvanced_enabled as $item){
	echo $this->__("				%s : true,\n",$item );
}
?>
				style: {
					submissionForm: {
						colourTop: '<?php echo $_style_submissionform_colourtop  ?>', //Default #4F5F6F
						colourButton: '<?php echo $_style_submissionform_colourbutton  ?>', //Default #5DADE2
						font: '<?php echo $_style_submissionform_font  ?>'//Default "Open Sans"
					},
					taggingTitle: {
						font: {
							family: '<?php echo $_style_taggingtitle_font_family  ?>',
							style: '<?php echo $_style_taggingtitle_font_style  ?>',
							weight: '<?php echo $_style_taggingtitle_font_weight  ?>',
							color: '<?php echo $_style_taggingtitle_font_color  ?>',
							size: '<?php echo $_style_taggingtitle_font_size  ?>'
						}
					},
					thumbnail: {
						bg: {
							color: '<?php echo $_style_thumbnail_bg_color ?>'
						},
						border: {
							color: '<?php echo $_style_thumbnail_border_color ?>'
						}
					},
					<?php if($_style_carousel_bg_color): ?>
					carousel: {
						bg: {
							color: '<?php echo $_style_carousel_bg_color  ?>'
						}
					},<?php endif; ?>
					popup: {
						bg: {
							color: '<?php echo $_style_popup_bg_color  ?>'
						},
						title: {
							font: {
								family: '<?php echo $_style_popup_title_font_family  ?>',
								style: '<?php echo $_style_popup_title_font_style  ?>',
								weight: '<?php echo $_style_popup_title_font_weight  ?>',
								color: '<?php echo $_style_popup_title_font_color  ?>'
							}
						},
						source: {
							font: {
								family: '<?php echo $_style_source_font_family  ?>',
								style: '<?php echo $_style_source_font_style ?>',
								weight: '<?php echo $_style_source_font_weight ?>',
								color: '<?php echo $_style_source_font_color ?>'
							}
						},
						product_caption_shop: {
							font: {
								family: '<?php echo $_style_productcaptionshop_font_family  ?>',
								style: '<?php echo $_style_productcaptionshop_font_style  ?>',
								weight: '<?php echo $_style_productcaptionshop_font_weight  ?>',
								color: '<?php echo $_style_productcaptionshop_font_color  ?>'
							}
						},
						product_description: {
							font: {
								family: '<?php echo $_style_productdescription_font_family ?>',
								style: '<?php echo $_style_productdescription_font_style ?>',
								weight: '<?php echo $_style_productdescription_font_weight ?>',
								color: '<?php echo $_style_productdescription_font_color ?>'
							}
						}
					}
				},
				<?php echo $_additional_params ?>
            };
				var script = document.createElement('script');
				script.async = true;
				script.src = '//static.photoslurp.com/widget/v2/<?php echo ($_widget -> getBundledJquery())?'widget_loader_jquery':'widget_loader';?>.js';
				var entry = document.getElementsByTagName('script')[0];
				entry.parentNode.insertBefore(script, entry);
        })();

    </script>
	<a href="//hi.photoslurp.com/partners/<?php echo $_widget->getUserName(); ?>?utm_source=referral&utm_medium=powered-by-photoslurp" target="_blank" class="ps-poweredby-link" title="Powered by Photoslurp">
		<div class="ps-logo-widget-carousel"></div>
	</a>
</div>

<?php endif; ?>
